* IcedTea7 2.4.3 release.

diff --git a/patches/icedtea-patch.diff b/patches/icedtea-patch.diff
--- a/patches/icedtea-patch.diff
+++ b/patches/icedtea-patch.diff
@@ -7,9 +7,9 @@ Description: Handle EXTRA_* flags into icedtea
  - Rename hotspot source and debian patches for zerovm build
 Author: Damien Raude-Morvan <drazzib@debian.org>, Matthias Klose <doko@ubuntu.com>
  
---- Makefile.am.orig
+--- Makefile.am
 +++ Makefile.am
-@@ -133,7 +133,7 @@
+@@ -150,7 +150,7 @@
  IT_JAVACFLAGS=$(IT_JAVAC_SETTINGS) -source $(IT_LANGUAGE_SOURCE_VERSION) -target $(IT_CLASS_TARGET_VERSION)
  
  # Flags
@@ -18,7 +18,7 @@ Author: Damien Raude-Morvan <drazzib@debian.org>, Matthias Klose <doko@ubuntu.co
  
  # Conditional defintions
  
-@@ -1477,9 +1477,6 @@
+@@ -1520,9 +1520,6 @@
  	  echo "DISTRO_PACKAGE_VERSION=$(PKGVERSION)" \
  	    >>openjdk/jdk/make/common/shared/Defs.gmk ;
  endif
@@ -28,7 +28,7 @@ Author: Damien Raude-Morvan <drazzib@debian.org>, Matthias Klose <doko@ubuntu.co
  	if test x"$(VERSION_SUFFIX)" != "x"; then \
  	  ver_suffix="-$(VERSION_SUFFIX)"; \
  	fi ; \
-@@ -1945,7 +1942,7 @@
+@@ -2214,7 +2211,7 @@
  	 -I$(PULSE_JAVA_NATIVE_BUILDDIR) -o $@ -c $<
  
  $(PULSE_JAVA_NATIVE_BUILDDIR)/libpulse-java.so: $(PULSE_JAVA_NATIVE_OBJECTS)
@@ -37,7 +37,7 @@ Author: Damien Raude-Morvan <drazzib@debian.org>, Matthias Klose <doko@ubuntu.co
  	 -o $(PULSE_JAVA_NATIVE_BUILDDIR)/libpulse-java.so
  
  endif
-@@ -2013,7 +2010,8 @@
+@@ -2282,7 +2279,8 @@
  if BUILD_JAMVM
  	cd jamvm/jamvm && \
  	./autogen.sh --with-java-runtime-library=openjdk7 \
@@ -47,7 +47,7 @@ Author: Damien Raude-Morvan <drazzib@debian.org>, Matthias Klose <doko@ubuntu.co
  	$(MAKE) ; \
  	$(MAKE) install
  	mkdir -p $(abs_top_builddir)/jamvm/install/hotspot/jre/lib/$(INSTALL_ARCH_DIR)/server
-@@ -2082,7 +2080,8 @@
+@@ -2351,7 +2349,8 @@
  	  --with-java-runtime-library=openjdk7 \
  	  --with-java-runtime-library-prefix=$(abs_top_builddir)/openjdk \
  	  --with-java-runtime-library-classes=$(RUNTIME) \
@@ -57,7 +57,7 @@ Author: Damien Raude-Morvan <drazzib@debian.org>, Matthias Klose <doko@ubuntu.co
  	$(ARCH_PREFIX) $(MAKE) -j$(PARALLEL_JOBS) install
  	ln -sf server $(abs_top_builddir)/cacao/install/jre/lib/$(INSTALL_ARCH_DIR)/client
  	touch $(abs_top_builddir)/cacao/install/jre/lib/$(INSTALL_ARCH_DIR)/server/Xusage.txt
-@@ -2158,7 +2157,7 @@
+@@ -2427,7 +2426,7 @@
  			'--with-javac=% '--with-javac=% \
  			'--with-rmic=% '--with-additional-vms=% \
  			'--disable-bootstrap% '--enable-bootstrap% , \
@@ -66,7 +66,7 @@ Author: Damien Raude-Morvan <drazzib@debian.org>, Matthias Klose <doko@ubuntu.co
  	$(foreach i, openjdk hotspot corba jaxp jaxws jdk langtools, \
  	  $(if $(findstring --with-$(i)-src-zip=, $(CONFIGURE_ARGS)),, --with-$(i)-src-zip=$(abs_top_builddir)/$(i).tar.gz))
  
-@@ -2168,7 +2167,7 @@
+@@ -2437,7 +2436,7 @@
  	BUILD_JAXWS=false     ALT_JAXWS_DIST=$(BUILD_OUTPUT_DIR)/jaxws/dist \
  	BUILD_CORBA=false     ALT_CORBA_DIST=$(BUILD_OUTPUT_DIR)/corba/dist \
  	BUILD_JDK=false \
@@ -75,24 +75,194 @@ Author: Damien Raude-Morvan <drazzib@debian.org>, Matthias Klose <doko@ubuntu.co
  
  stamps/add-zero.stamp: stamps/icedtea.stamp
  	mkdir -p stamps
---- patches/jamvm/remove-sun.misc.Perf-debug-code.patch
-+++ patches/jamvm/remove-sun.misc.Perf-debug-code.patch
-@@ -34,9 +34,9 @@
-              if (resolve) {
- Index: openjdk/jdk/src/share/classes/java/util/zip/ZipFile.java
- ===================================================================
----- openjdk.orig/jdk/src/share/classes/java/util/zip/ZipFile.java	2011-06-28 18:56:56.994704556 +0200
--+++ openjdk/jdk/src/share/classes/java/util/zip/ZipFile.java	2011-06-28 18:57:11.514776567 +0200
--@@ -212,8 +212,6 @@
-+--- openjdk/jdk/src/share/classes/java/util/zip/ZipFile.java~	2013-06-21 22:46:14.000000000 +0200
-++++ openjdk/jdk/src/share/classes/java/util/zip/ZipFile.java	2013-06-28 17:08:07.597635788 +0200
-+@@ -213,8 +213,6 @@
-          this.zc = ZipCoder.get(charset);
-          long t0 = System.nanoTime();
-          jzfile = open(name, mode, file.lastModified(), usemmap);
-@@ -44,4 +44,4 @@
- -        sun.misc.PerfCounter.getZipFileCount().increment();
-          this.name = name;
-          this.total = getTotal(jzfile);
--     }
-+         this.locsig = startsWithLOC(jzfile);
+--- Makefile.in
++++ Makefile.in
+@@ -638,7 +638,7 @@
+ IT_JAVACFLAGS = $(IT_JAVAC_SETTINGS) -source $(IT_LANGUAGE_SOURCE_VERSION) -target $(IT_CLASS_TARGET_VERSION)
+ 
+ # Flags
+-IT_CFLAGS = $(CFLAGS) $(ARCHFLAG)
++IT_CFLAGS = $(CFLAGS) $(ARCHFLAG) $(EXTRA_CFLAGS_IT)
+ @USE_HG_FALSE@OPENJDK_SRC_ZIP = openjdk.tar.gz
+ 
+ # Conditional defintions
+@@ -989,9 +989,10 @@
+ 	--disable-docs $(filter-out '--with-jdk-home=% '--with-ecj=% \
+ 	'--with-java=% '--with-javah=% '--with-javac=% '--with-javac=% \
+ 	'--with-rmic=% '--with-additional-vms=% '--disable-bootstrap% \
+-	'--enable-bootstrap% , $(CONFIGURE_ARGS)) $(foreach i, openjdk \
+-	hotspot corba jaxp jaxws jdk langtools, $(if $(findstring \
+-	--with-$(i)-src-zip=, $(CONFIGURE_ARGS)),, \
++	'--enable-bootstrap% , $(subst \
++	hotspot-default.tar,hotspot-zero.tar,$(CONFIGURE_ARGS))) \
++	$(foreach i, openjdk hotspot corba jaxp jaxws jdk langtools, \
++	$(if $(findstring --with-$(i)-src-zip=, $(CONFIGURE_ARGS)),, \
+ 	--with-$(i)-src-zip=$(abs_top_builddir)/$(i).tar.gz))
+ ADD_ZERO_EXTRA_BUILD_ENV = \
+ 	BUILD_LANGTOOLS=false ALT_LANGTOOLS_DIST=$(BUILD_OUTPUT_DIR)/langtools/dist \
+@@ -999,7 +1000,7 @@
+ 	BUILD_JAXWS=false     ALT_JAXWS_DIST=$(BUILD_OUTPUT_DIR)/jaxws/dist \
+ 	BUILD_CORBA=false     ALT_CORBA_DIST=$(BUILD_OUTPUT_DIR)/corba/dist \
+ 	BUILD_JDK=false \
+-	DISTRIBUTION_PATCHES='$(foreach p,$(DISTRIBUTION_PATCHES),$(if $(findstring cacao,$(p)),,$(if $(findstring jamvm,$(p)),,$(p))))'
++	DISTRIBUTION_PATCHES='$(foreach p,$(subst -default,-zero,$(DISTRIBUTION_PATCHES)),$(if $(findstring cacao,$(p)),,$(if $(findstring jamvm,$(p)),,$(p))))'
+ 
+ 
+ # FIXME: this might need some adjustment for other OS than Linux
+@@ -2019,9 +2020,6 @@
+ 	echo "DISTRO_NAME=$(DIST_NAME)" >>openjdk/jdk/make/common/shared/Defs.gmk ;
+ @HAS_PKGVERSION_TRUE@	  echo "DISTRO_PACKAGE_VERSION=$(PKGVERSION)" \
+ @HAS_PKGVERSION_TRUE@	    >>openjdk/jdk/make/common/shared/Defs.gmk ;
+-	if test x"$(PROJECT_NAME)" != "xjdk7" && test x"$(PROJECT_NAME)" != "xicedtea"; then \
+-	  proj_suffix="-$(PROJECT_NAME)"; \
+-	fi ; \
+ 	if test x"$(VERSION_SUFFIX)" != "x"; then \
+ 	  ver_suffix="-$(VERSION_SUFFIX)"; \
+ 	fi ; \
+@@ -2649,7 +2647,7 @@
+ @ENABLE_PULSE_JAVA_TRUE@	 -I$(PULSE_JAVA_NATIVE_BUILDDIR) -o $@ -c $<
+ 
+ @ENABLE_PULSE_JAVA_TRUE@$(PULSE_JAVA_NATIVE_BUILDDIR)/libpulse-java.so: $(PULSE_JAVA_NATIVE_OBJECTS)
+-@ENABLE_PULSE_JAVA_TRUE@	$(CC) $(LDFLAGS) -shared $(PULSE_JAVA_NATIVE_OBJECTS) $(LIBPULSE_LIBS) \
++@ENABLE_PULSE_JAVA_TRUE@	$(CC) $(LDFLAGS) $(EXTRA_LDFLAGS_IT) -shared $(PULSE_JAVA_NATIVE_OBJECTS) $(LIBPULSE_LIBS) \
+ @ENABLE_PULSE_JAVA_TRUE@	 -o $(PULSE_JAVA_NATIVE_BUILDDIR)/libpulse-java.so
+ 
+ clean-pulse-java:
+@@ -2710,7 +2708,8 @@
+ stamps/jamvm.stamp: $(OPENJDK_TREE) stamps/rt.stamp
+ @BUILD_JAMVM_TRUE@	cd jamvm/jamvm && \
+ @BUILD_JAMVM_TRUE@	./autogen.sh --with-java-runtime-library=openjdk7 \
+-@BUILD_JAMVM_TRUE@	  --prefix=$(abs_top_builddir)/jamvm/install ; \
++@BUILD_JAMVM_TRUE@	  --prefix=$(abs_top_builddir)/jamvm/install \
++@BUILD_JAMVM_TRUE@	  CFLAGS='$(EXTRA_CFLAGS_JAMVM)' LDFLAGS='$(EXTRA_LDFLAGS_JAMVM)' CPPFLAGS='$(EXTRA_CPPFLAGS_JAMVM)' CXXFLAGS='$(EXTRA_CXXFLAGS_JAMVM)'; \
+ @BUILD_JAMVM_TRUE@	$(MAKE) ; \
+ @BUILD_JAMVM_TRUE@	$(MAKE) install
+ @BUILD_JAMVM_TRUE@	mkdir -p $(abs_top_builddir)/jamvm/install/hotspot/jre/lib/$(INSTALL_ARCH_DIR)/server
+@@ -2770,7 +2769,8 @@
+ @BUILD_CACAO_TRUE@@USE_SYSTEM_CACAO_FALSE@	  --with-java-runtime-library=openjdk7 \
+ @BUILD_CACAO_TRUE@@USE_SYSTEM_CACAO_FALSE@	  --with-java-runtime-library-prefix=$(abs_top_builddir)/openjdk \
+ @BUILD_CACAO_TRUE@@USE_SYSTEM_CACAO_FALSE@	  --with-java-runtime-library-classes=$(RUNTIME) \
+-@BUILD_CACAO_TRUE@@USE_SYSTEM_CACAO_FALSE@	  --enable-jre-layout $(CACAO_CONFIGURE_ARGS); \
++@BUILD_CACAO_TRUE@@USE_SYSTEM_CACAO_FALSE@	  --enable-jre-layout $(CACAO_CONFIGURE_ARGS) \
++@BUILD_CACAO_TRUE@@USE_SYSTEM_CACAO_FALSE@	  CFLAGS='$(EXTRA_CFLAGS_CACAO)' LDFLAGS='$(EXTRA_LDFLAGS_CACAO)' CPPFLAGS='$(EXTRA_CPPFLAGS_CACAO)' CXXFLAGS='$(EXTRA_CXXFLAGS_CACAO)'; \
+ @BUILD_CACAO_TRUE@@USE_SYSTEM_CACAO_FALSE@	$(ARCH_PREFIX) $(MAKE) -j$(PARALLEL_JOBS) install
+ @BUILD_CACAO_TRUE@@USE_SYSTEM_CACAO_FALSE@	ln -sf server $(abs_top_builddir)/cacao/install/jre/lib/$(INSTALL_ARCH_DIR)/client
+ @BUILD_CACAO_TRUE@@USE_SYSTEM_CACAO_FALSE@	touch $(abs_top_builddir)/cacao/install/jre/lib/$(INSTALL_ARCH_DIR)/server/Xusage.txt
+--- acinclude.m4
++++ acinclude.m4
+@@ -1954,7 +1954,7 @@
+   AC_MSG_RESULT(${ENABLE_SYSTEM_LCMS})
+   if test x"${ENABLE_SYSTEM_LCMS}" = "xyes"; then
+     dnl Check for LCMS2 headers and libraries.
+-    PKG_CHECK_MODULES(LCMS2, lcms2 >= 2.5,[LCMS2_FOUND=yes],[LCMS2_FOUND=no])
++    PKG_CHECK_MODULES(LCMS2, lcms2,[LCMS2_FOUND=yes],[LCMS2_FOUND=no])
+     if test "x${LCMS2_FOUND}" = xno
+     then
+       AC_MSG_ERROR([Could not find LCMS >= 2.5; install it or build with --disable-system-lcms to use the in-tree copy.])
+--- configure
++++ configure
+@@ -13396,12 +13396,12 @@
+     pkg_cv_LCMS2_CFLAGS="$LCMS2_CFLAGS"
+  elif test -n "$PKG_CONFIG"; then
+     if test -n "$PKG_CONFIG" && \
+-    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lcms2 >= 2.5\""; } >&5
+-  ($PKG_CONFIG --exists --print-errors "lcms2 >= 2.5") 2>&5
++    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lcms2\""; } >&5
++  ($PKG_CONFIG --exists --print-errors "lcms2") 2>&5
+   ac_status=$?
+   $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+   test $ac_status = 0; }; then
+-  pkg_cv_LCMS2_CFLAGS=`$PKG_CONFIG --cflags "lcms2 >= 2.5" 2>/dev/null`
++  pkg_cv_LCMS2_CFLAGS=`$PKG_CONFIG --cflags "lcms2" 2>/dev/null`
+ 		      test "x$?" != "x0" && pkg_failed=yes
+ else
+   pkg_failed=yes
+@@ -13413,12 +13413,12 @@
+     pkg_cv_LCMS2_LIBS="$LCMS2_LIBS"
+  elif test -n "$PKG_CONFIG"; then
+     if test -n "$PKG_CONFIG" && \
+-    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lcms2 >= 2.5\""; } >&5
+-  ($PKG_CONFIG --exists --print-errors "lcms2 >= 2.5") 2>&5
++    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lcms2\""; } >&5
++  ($PKG_CONFIG --exists --print-errors "lcms2") 2>&5
+   ac_status=$?
+   $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+   test $ac_status = 0; }; then
+-  pkg_cv_LCMS2_LIBS=`$PKG_CONFIG --libs "lcms2 >= 2.5" 2>/dev/null`
++  pkg_cv_LCMS2_LIBS=`$PKG_CONFIG --libs "lcms2" 2>/dev/null`
+ 		      test "x$?" != "x0" && pkg_failed=yes
+ else
+   pkg_failed=yes
+@@ -13439,9 +13439,9 @@
+         _pkg_short_errors_supported=no
+ fi
+         if test $_pkg_short_errors_supported = yes; then
+-	        LCMS2_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "lcms2 >= 2.5" 2>&1`
++	        LCMS2_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "lcms2" 2>&1`
+         else
+-	        LCMS2_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "lcms2 >= 2.5" 2>&1`
++	        LCMS2_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "lcms2" 2>&1`
+         fi
+ 	# Put the nasty error message in config.log where it belongs
+ 	echo "$LCMS2_PKG_ERRORS" >&5
+--- patches/boot/test_gamma.patch
++++ patches/boot/test_gamma.patch
+@@ -1,47 +1,45 @@
+-diff -Nru ../openjdk.orig/openjdk-boot/hotspot/make/linux/Makefile openjdk-boot/hotspot/make/linux/Makefile
+---- ../openjdk.orig/openjdk-boot/hotspot/make/linux/Makefile	2009-10-30 17:37:07.000000000 +0000
+-+++ openjdk-boot/hotspot/make/linux/Makefile	2009-10-30 17:45:40.000000000 +0000
+-@@ -287,42 +287,36 @@
++--- openjdk-boot/hotspot/make/linux/Makefile.orig	2013-11-21 09:58:19.000000000 +0100
+++++ openjdk-boot/hotspot/make/linux/Makefile	2013-11-21 10:14:49.044885935 +0100
++@@ -290,42 +290,36 @@
+  
+  $(TARGETS_C2):  $(SUBDIRS_C2)
+  	cd $(OSNAME)_$(BUILDARCH)_compiler2/$@ && $(MAKE) $(MFLAGS)
+--	cd $(OSNAME)_$(BUILDARCH)_compiler2/$@ && ./test_gamma
++-	cd $(OSNAME)_$(BUILDARCH)_compiler2/$@ && $(taskset) ./test_gamma
+  ifdef INSTALL
+  	cd $(OSNAME)_$(BUILDARCH)_compiler2/$@ && $(MAKE) $(MFLAGS) install
+  endif
+  
+  $(TARGETS_TIERED):  $(SUBDIRS_TIERED)
+  	cd $(OSNAME)_$(BUILDARCH)_tiered/$(patsubst %tiered,%,$@) && $(MAKE) $(MFLAGS)
+--	cd $(OSNAME)_$(BUILDARCH)_tiered/$(patsubst %tiered,%,$@) && ./test_gamma
++-	cd $(OSNAME)_$(BUILDARCH)_tiered/$(patsubst %tiered,%,$@) && $(taskset) ./test_gamma
+  ifdef INSTALL
+  	cd $(OSNAME)_$(BUILDARCH)_tiered/$(patsubst %tiered,%,$@) && $(MAKE) $(MFLAGS) install
+  endif
+  
+  $(TARGETS_C1):  $(SUBDIRS_C1)
+  	cd $(OSNAME)_$(BUILDARCH)_compiler1/$(patsubst %1,%,$@) && $(MAKE) $(MFLAGS)
+--	cd $(OSNAME)_$(BUILDARCH)_compiler1/$(patsubst %1,%,$@) && ./test_gamma
++-	cd $(OSNAME)_$(BUILDARCH)_compiler1/$(patsubst %1,%,$@) && $(taskset) ./test_gamma
+  ifdef INSTALL
+  	cd $(OSNAME)_$(BUILDARCH)_compiler1/$(patsubst %1,%,$@) && $(MAKE) $(MFLAGS) install
+  endif
+  
+  $(TARGETS_CORE):  $(SUBDIRS_CORE)
+  	cd $(OSNAME)_$(BUILDARCH)_core/$(patsubst %core,%,$@) && $(MAKE) $(MFLAGS)
+--	cd $(OSNAME)_$(BUILDARCH)_core/$(patsubst %core,%,$@) && ./test_gamma
++-	cd $(OSNAME)_$(BUILDARCH)_core/$(patsubst %core,%,$@) && $(taskset) ./test_gamma
+  ifdef INSTALL
+  	cd $(OSNAME)_$(BUILDARCH)_core/$(patsubst %core,%,$@) && $(MAKE) $(MFLAGS) install
+  endif
+  
+  $(TARGETS_ZERO):  $(SUBDIRS_ZERO)
+  	cd $(OSNAME)_$(VARIANTARCH)_zero/$(patsubst %zero,%,$@) && $(MAKE) $(MFLAGS)
+--	cd $(OSNAME)_$(VARIANTARCH)_zero/$(patsubst %zero,%,$@) && ./test_gamma
++-	cd $(OSNAME)_$(VARIANTARCH)_zero/$(patsubst %zero,%,$@) && $(taskset) ./test_gamma
+  ifdef INSTALL
+  	cd $(OSNAME)_$(VARIANTARCH)_zero/$(patsubst %zero,%,$@) && $(MAKE) $(MFLAGS) install
+  endif
+  
+  $(TARGETS_SHARK):  $(SUBDIRS_SHARK)
+-    cd $(OSNAME)_$(VARIANTARCH)_shark/$(patsubst %shark,%,$@) && $(MAKE) $(MFLAGS)
+--   cd $(OSNAME)_$(VARIANTARCH)_shark/$(patsubst %shark,%,$@) && ./test_gamma
++ 	cd $(OSNAME)_$(VARIANTARCH)_shark/$(patsubst %shark,%,$@) && $(MAKE) $(MFLAGS)
++-	cd $(OSNAME)_$(VARIANTARCH)_shark/$(patsubst %shark,%,$@) && $(taskset) ./test_gamma
+  ifdef INSTALL
+-    cd $(OSNAME)_$(VARIANTARCH)_shark/$(patsubst %shark,%,$@) && $(MAKE) $(MFLAGS) install
++ 	cd $(OSNAME)_$(VARIANTARCH)_shark/$(patsubst %shark,%,$@) && $(MAKE) $(MFLAGS) install
+  endif
+- 
