openjdk-7 (7u9-2.3.5~pre1-1) experimental; urgency=low
  * IcedTea7 2.3.5 snapshot, taken from the icedtea7-2.3 branch.
    - Disable bootstrap builds, currently broken in IcedTea.
  * Fix font suggestion for indic fonts in wheezy.
  * Fix fontconfig definitions for japanese and korean fonts, fixing
    compilation of the fontconfig file.
  * Add Built-Using: rhino attribute for the -lib package.
  * Don't use concurrent features to rewrite the rhino jar file.
  * Enable class data sharing for the hotspot server VM.

 -- Matthias Klose <doko@ubuntu.com>  Sun, 10 Feb 2013 21:42:44 +0100

diff --git a/JB-jre-headless.postinst.in b/JB-jre-headless.postinst.in
--- a/JB-jre-headless.postinst.in
+++ b/JB-jre-headless.postinst.in
@@ -115,6 +115,18 @@ configure)
 	fi
 	rm -f $log
     esac
+    case @archdir@ in amd64|i386|sparc)
+	rm -f $basedir/jre/lib/@archdir@/server/classes.jsa
+	log=$(tempfile)
+	if ! $basedir/bin/java -server -Xshare:dump > $log; then
+	    cat >&2 $log
+	    rm -f $log
+	    # this may fail on some machines/configurations, just ignore it.
+	    echo >&2 "ignoring dump failure"
+	    #exit 1
+	fi
+	rm -f $log
+    esac
 
     if [ -n "$multiarch" ]; then
 	if [ ! -h /@basedir@/jre/lib/zi ] && [ -d /@basedir@/jre/lib/zi ]; then
