openjdk-6 (6b08-0ubuntu1) hardy; urgency=low
  * New code drop (b08).
  * Update IcedTea build infrastructure.
  * Move binfmt-support references from -jre to -jre-headless package.
  * Don't fail on purge, if /var/lib/binfmts/openjdk-6 is missing. LP: #206721.
  * Only use the basename for icons in desktop files. LP: #207413.
  * Install javaws(1). LP: #191297.
  * Install a wrapper script for javaws, which calls `javaws -viewer' if no
    arguments are given (or else starting javaws from the desktop menu
    would not do anything).
  * debian/JB-web-start.applications.in: Remove the -viewer option from command.

 -- Matthias Klose <doko@ubuntu.com>  Fri, 28 Mar 2008 16:10:32 +0000

openjdk-6 (6b07-0ubuntu1) hardy; urgency=low

  * New code drop (b07).
  * Update IcedTea build infrastructure.
  * debian/copyright: Update to OpenJDK Trademark Notice v1.1.

 -- Matthias Klose <doko@ubuntu.com>  Sat, 22 Mar 2008 22:41:42 +0100

diff --git a/JB-jre-headless.prerm.in b/JB-jre-headless.prerm.in
--- a/JB-jre-headless.prerm.in
+++ b/JB-jre-headless.prerm.in
@@ -11,8 +11,12 @@ for i in $jre_tools; do
 done
 
 if [ remove = "$1" ] && [ -x /usr/sbin/update-binfmts ]; then
-    /usr/sbin/update-binfmts --package @basename@ \
-      --remove @basename@ $basedir/jre/lib/jexec
+    if [ -e /var/lib/binfmts/@basename@ ]; then
+	/usr/sbin/update-binfmts --package @basename@ \
+	    --remove @basename@ $basedir/jre/lib/jexec
+    else
+	echo >&2 "/var/lib/binfmts/@basename@ missing, not calling update-binfmts --remove"
+    fi
 fi
 
 #DEBHELPER#
